# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @angular/cli@latest
    - run: npm install
    - run: ng build --prod=true
    - run: ng test

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure Deploy to Storage
      uses: azure/CLI@v1
      env:
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_STORAGE_NAME: ${{ secrets.AZURE_STORAGE_NAME }}
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az storage blob upload-batch -s ./dist -d \$web --account-name $AZURE_STORAGE_NAME
          az storage account show -n $AZURE_STORAGE_NAME -g $AZURE_RESOURCE_GROUP --query "primaryEndpoints.web" --output tsv
